version: '2'

services:
    db:
        container_name: sf_pgsql
        image: postgres:9
        volumes:
            - "./data/db:/var/lib/postgresql"
        environment:
            POSTGRES_DB: ${DB}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.3
    php:
        container_name: sf_phpfpm
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - "80:8000"
        networks:
            vpcbr:
                ipv4_address: 10.5.0.2
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - db

volumes:
    esdata1:
        driver: local
    app-sync:
        external: true

networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
